services:
  - type: web
    name: upglow
    runtime: node
    region: oregon
    plan: free
    buildCommand: bun install && bunx prisma generate && bun run build
    startCommand: bun run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: upglow-db
          property: connectionString
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NODE_VERSION
        value: 20.11.0

databases:
  - name: upglow-db
    databaseName: upglow
    user: upglow
    region: oregon
    plan: free

